import os
import sys
import json
import subprocess
from pathlib import Path
from dotenv import dotenv_values

# Ensure src/ is on sys.path
src_path = str(Path(__file__).resolve().parent / "src")
if src_path not in sys.path:
    sys.path.insert(0, src_path)

from jev.models import State, Subgoal
from jev.workspace import Workspace
from jev.gatekeeper import Gatekeeper
from jev.engine import node_implement, node_gate
from langchain_google_genai import ChatGoogleGenerativeAI


def run_pipeline():
    os.environ["SKIP_LIVE_TEST"] = "1"
    print("=" * 70, flush=True)
    print("SUB-STEP 7a: Real Pipeline Execution with Gemini 3.5 Flash Lite", flush=True)
    print("=" * 70, flush=True)

    # 1. Environment & Config
    env_file = Path(".env").resolve()
    if not env_file.exists():
        raise FileNotFoundError(f".env file not found at {env_file}")

    parsed_env = dotenv_values(env_file)
    google_api_key = parsed_env.get("GOOGLE_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not google_api_key:
        raise ValueError("GOOGLE_API_KEY not found in .env or environment")
    os.environ["GOOGLE_API_KEY"] = google_api_key

    # 2. Ensure git baseline is clean and committed without target docstring
    print("[1/5] Ensuring clean baseline commit in git...", flush=True)
    workspace_file = Path("src/jev/workspace.py")
    if workspace_file.exists():
        ws_content = workspace_file.read_text(encoding="utf-8")
        target_doc = '    def run_read_tool(self, cmd: str, args: Optional[List[str]] = None) -> str:\n        """Executes read-only CLI commands in worktree_dir and returns stdout or stderr."""\n'
        clean_target = '    def run_read_tool(self, cmd: str, args: Optional[List[str]] = None) -> str:\n'
        if target_doc in ws_content:
            workspace_file.write_text(ws_content.replace(target_doc, clean_target), encoding="utf-8")

    subprocess.run(["git", "add", "-A"], cwd=Path.cwd(), check=True)
    status_check = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=Path.cwd(),
        capture_output=True,
        text=True,
    )
    if status_check.stdout.strip():
        subprocess.run(
            ["git", "commit", "-m", "Commit baseline before live subgoal execution"],
            cwd=Path.cwd(),
            check=True,
        )

    workspace = Workspace(repo_dir=Path.cwd().resolve())
    gatekeeper = Gatekeeper(env_file=env_file)

    print("[2/5] Initializing Gemini 3.5 Flash Lite LLM...", flush=True)
    llm = ChatGoogleGenerativeAI(
        model="gemini-3.5-flash-lite",
        google_api_key=google_api_key,
        temperature=0.0,
        max_retries=5,
    )

    # 3. Subgoal Definition
    subgoal = Subgoal(
        description="Add a docstring to Workspace.run_read_tool in src/jev/workspace.py explaining that it executes read-only CLI commands in worktree_dir and returns stdout or stderr.",
        scope=["src/jev/workspace.py"],
        expects_tests=False,
    )

    state: State = {
        "ticket": "Sub-step 7a: Add docstring to Workspace.run_read_tool in src/jev/workspace.py",
        "plan_queue": [],
        "current_subgoal": subgoal,
        "mechanical_strike_count": 0,
        "semantic_strike_count": 0,
        "trajectory": [],
    }

    # Verify workspace is clean before starting
    diff_before = workspace.get_staged_diff()
    print(f"Pre-run staged diff is empty: {diff_before == ''}", flush=True)

    # 4. Step 4: Run node_implement (real Gemini call using gemini-3.5-flash-lite)
    print("\n[3/5] Calling node_implement (Gemini 3.5 Flash Lite)...", flush=True)
    state = node_implement(state, workspace=workspace, llm=llm)

    # 5. Extract and print the diff generated by Gemini
    diff_after_implement = workspace.get_staged_diff()
    print("\n" + "=" * 70, flush=True)
    print("DIFF GENERATED BY GEMINI 3.5 FLASH LITE:", flush=True)
    print("=" * 70, flush=True)
    print(diff_after_implement if diff_after_implement else "(empty diff)", flush=True)
    print("=" * 70, flush=True)

    traj_implement = [t for t in state.get("trajectory", []) if t.get("node") == "implement"]
    tool_calls = traj_implement[-1].get("tool_calls", []) if traj_implement else []
    print(f"\nTool calls executed by Gemini: {json.dumps(tool_calls, indent=2)}", flush=True)

    # 6. Step 5: Run node_gate (real Tier 0 checks -> Gatekeeper.validate_subgoal real Jev call)
    print("\n[4/5] Calling node_gate (Tier 0 mechanical -> Tier 1 Jev Gatekeeper)...", flush=True)
    state = node_gate(state, workspace=workspace, gatekeeper=gatekeeper)

    gate_status = state.get("gate_status")
    last_feedback = state.get("last_feedback")
    mech_strikes = state.get("mechanical_strike_count")
    sem_strikes = state.get("semantic_strike_count")

    print("\n" + "=" * 70, flush=True)
    print(f"GATE STATUS: {gate_status}", flush=True)
    print(f"Mechanical strikes: {mech_strikes}, Semantic strikes: {sem_strikes}", flush=True)
    print(f"Last feedback / reason: {last_feedback}", flush=True)
    print("=" * 70, flush=True)

    # Check git log to see recent commit
    log_res = subprocess.run(
        ["git", "log", "-n", "3", "--oneline"],
        cwd=Path.cwd(),
        capture_output=True,
        text=True,
    )
    print("\nRecent git commits:", flush=True)
    print(log_res.stdout, flush=True)

    # Check git status
    status_res = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=Path.cwd(),
        capture_output=True,
        text=True,
    )
    print("Git status after gate:", flush=True)
    print(status_res.stdout or "(clean)", flush=True)

    committed = gate_status == "passed"
    print(f"\n[5/5] Final Outcome: {'COMMITTED' if committed else 'ROLLED BACK'}", flush=True)

    # Save complete run data to json
    report = {
        "subgoal": subgoal.model_dump(),
        "diff_generated": diff_after_implement,
        "tool_calls": tool_calls,
        "gate_status": gate_status,
        "mechanical_strikes": mech_strikes,
        "semantic_strikes": sem_strikes,
        "last_feedback": last_feedback,
        "committed": committed,
        "recent_commits": log_res.stdout.strip().splitlines(),
    }

    Path("substep_7a_report.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    print("\nReport saved to substep_7a_report.json", flush=True)
    return report


if __name__ == "__main__":
    run_pipeline()
